package calcul;


/**
* calcul/calcul_montants.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/spec.idl
* Tuesday, December 7, 2021 8:40:21 PM WAT
*/

public interface calcul_montants extends calcul_montantsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul_montants
